### Get a USER RECORD by ID
GET http://localhost:5500/api/users/af1ef80a-ab9e-48d3-b361-b4010967959a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIzZDkwY2E2Ni0xYmY3LTRlYzUtODVmNi02YTBlZTMxMzMzMzkiLCJlbWFpbCI6ImJvYmJ5QGVtYWlsLmNvbSIsImlhdCI6MTcyMDM5NDcwNCwiZXhwIjoxNzIwMzk3NzA0fQ.bCzkAeY4jJ4AW8k3kHDxuvkKz2pjsyTJuMROt__Doc0



### Create a USER 1
POST http://localhost:5500/api/users
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "FirstMan",
  "email": "samlarrymarlian@email.com",
  "password": "lileunited",
  "phone": "07053005601"
}


### Create Organisation
POST http://localhost:5500/api/organisations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIzZDkwY2E2Ni0xYmY3LTRlYzUtODVmNi02YTBlZTMxMzMzMzkiLCJlbWFpbCI6ImJvYmJ5QGVtYWlsLmNvbSIsImlhdCI6MTcyMDM5NDcwNCwiZXhwIjoxNzIwMzk3NzA0fQ.bCzkAeY4jJ4AW8k3kHDxuvkKz2pjsyTJuMROt__Doc0

{
  "name": "Gramme Organisation2",
  "description": "This is Gram's Second organisation"
}

### Add User to Organisation
POST http://localhost:5500/api/organisations/1bc718d4-28d8-4f7a-be5a-ac63834586ab/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIzZDkwY2E2Ni0xYmY3LTRlYzUtODVmNi02YTBlZTMxMzMzMzkiLCJlbWFpbCI6ImJvYmJ5QGVtYWlsLmNvbSIsImlhdCI6MTcyMDM5NDcwNCwiZXhwIjoxNzIwMzk3NzA0fQ.bCzkAeY4jJ4AW8k3kHDxuvkKz2pjsyTJuMROt__Doc0

{
  "userId": "c5aa0d87-0c9d-4388-ba04-7af7e3b383ab"
}

### Get Single Organisation
GET http://localhost:5500/api/organisations/1bc718d4-28d8-4f7a-be5a-ac63834586ab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIzZDkwY2E2Ni0xYmY3LTRlYzUtODVmNi02YTBlZTMxMzMzMzkiLCJlbWFpbCI6ImJvYmJ5QGVtYWlsLmNvbSIsImlhdCI6MTcyMDM5NDcwNCwiZXhwIjoxNzIwMzk3NzA0fQ.bCzkAeY4jJ4AW8k3kHDxuvkKz2pjsyTJuMROt__Doc0



### Get User Organisations
GET http://localhost:5500/api/organisations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIzZDkwY2E2Ni0xYmY3LTRlYzUtODVmNi02YTBlZTMxMzMzMzkiLCJlbWFpbCI6ImJvYmJ5QGVtYWlsLmNvbSIsImlhdCI6MTcyMDM5NDcwNCwiZXhwIjoxNzIwMzk3NzA0fQ.bCzkAeY4jJ4AW8k3kHDxuvkKz2pjsyTJuMROt__Doc0


###List USERS
GET http://localhost:5500/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIzZDkwY2E2Ni0xYmY3LTRlYzUtODVmNi02YTBlZTMxMzMzMzkiLCJlbWFpbCI6ImJvYmJ5QGVtYWlsLmNvbSIsImlhdCI6MTcyMDM5NDcwNCwiZXhwIjoxNzIwMzk3NzA0fQ.bCzkAeY4jJ4AW8k3kHDxuvkKz2pjsyTJuMROt__Doc0

### LOGIN USER
POST http://localhost:5500/api/auth/login
Content-Type: application/json

{
  "email":"bobby@email.com",
  "password":"bob"
}

###REFRESH TOKENS
GET http://localhost:5500/api/auth/refresh_token

###

DELETE http://localhost:5500/api/auth/refresh_token
###

DELETE http://localhost:5500/api/users
