### Get a USER RECORD by ID
GET https://task-2-postgres.vercel.app/api/users/743a9e11-5885-466d-b5bb-11b96b76e878
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI3NDNhOWUxMS01ODg1LTQ2NmQtYjViYi0xMWI5NmI3NmU4NzgiLCJlbWFpbCI6InNhbWxhcnJ5bWFybGlhbkBnbWFpbC5jb20iLCJpYXQiOjE3MjA1MzA1MTIsImV4cCI6MTcyMDUzMzUxMn0.gOmK18VbBkUgisDlse9G-ECNsFh7oieu5_YqjgyngL4



### Create a USER 1
POST https://task-2-postgres.vercel.app/api/auth/register
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "FirstMan",
  "email": "samlarrymarlian@email.com",
  "password": "lileunited",
  "phone": "07053005601"
}


### Create Organisation
POST https://task-2-postgres.vercel.app/api/organisations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI3NDNhOWUxMS01ODg1LTQ2NmQtYjViYi0xMWI5NmI3NmU4NzgiLCJlbWFpbCI6InNhbWxhcnJ5bWFybGlhbkBnbWFpbC5jb20iLCJpYXQiOjE3MjA1MzA1MTIsImV4cCI6MTcyMDUzMzUxMn0.gOmK18VbBkUgisDlse9G-ECNsFh7oieu5_YqjgyngL4

{
  "name": "Gramme Organisation2",
  "description": "This is Gram's Second organisation"
}

### Add User to Organisation
POST https://task-2-postgres.vercel.app/api/organisations/1bc718d4-28d8-4f7a-be5a-ac63834586ab/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI3NDNhOWUxMS01ODg1LTQ2NmQtYjViYi0xMWI5NmI3NmU4NzgiLCJlbWFpbCI6InNhbWxhcnJ5bWFybGlhbkBnbWFpbC5jb20iLCJpYXQiOjE3MjA1MzA1MTIsImV4cCI6MTcyMDUzMzUxMn0.gOmK18VbBkUgisDlse9G-ECNsFh7oieu5_YqjgyngL4

{
  "userId": "c5aa0d87-0c9d-4388-ba04-7af7e3b383ab"
}

### Get Single Organisation
GET https://task-2-postgres.vercel.app/api/organisations/1bc718d4-28d8-4f7a-be5a-ac63834586ab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI3NDNhOWUxMS01ODg1LTQ2NmQtYjViYi0xMWI5NmI3NmU4NzgiLCJlbWFpbCI6InNhbWxhcnJ5bWFybGlhbkBnbWFpbC5jb20iLCJpYXQiOjE3MjA1MzA1MTIsImV4cCI6MTcyMDUzMzUxMn0.gOmK18VbBkUgisDlse9G-ECNsFh7oieu5_YqjgyngL4



### Get User Organisations
GET https://task-2-postgres.vercel.app/api/organisations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI3NDNhOWUxMS01ODg1LTQ2NmQtYjViYi0xMWI5NmI3NmU4NzgiLCJlbWFpbCI6InNhbWxhcnJ5bWFybGlhbkBnbWFpbC5jb20iLCJpYXQiOjE3MjA1MzA1MTIsImV4cCI6MTcyMDUzMzUxMn0.gOmK18VbBkUgisDlse9G-ECNsFh7oieu5_YqjgyngL4


###List USERS
GET https://task-2-postgres.vercel.app/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI3NDNhOWUxMS01ODg1LTQ2NmQtYjViYi0xMWI5NmI3NmU4NzgiLCJlbWFpbCI6InNhbWxhcnJ5bWFybGlhbkBnbWFpbC5jb20iLCJpYXQiOjE3MjA1MzA1MTIsImV4cCI6MTcyMDUzMzUxMn0.gOmK18VbBkUgisDlse9G-ECNsFh7oieu5_YqjgyngL4

### LOGIN USER
POST https://task-2-postgres.vercel.app/api/auth/login
Content-Type: application/json

{
  "email":"bobby@email.com",
  "password":"bob"
}

###REFRESH TOKENS
GET https://task-2-postgres.vercel.app/api/auth/refresh_token

###

DELETE https://task-2-postgres.vercel.app/api/auth/refresh_token
###

DELETE https://task-2-postgres.vercel.app/api/users
